apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: ds-prom
    access: proxy
    url: http://prometheus.lan:9090
    editable: false
    isDefault: false

  - name: Loki
    type: loki
    uid: ds-loki
    access: proxy
    url: http://loki.lan:3100
    jsonData:
      maxLines: 10000
    editable: false
    isDefault: false
